#!/usr/bin/env node
// Reads all *.bdf files under res/bdf, compresses each with pako (zlib
// deflate), base64-encodes the result, and writes src/embeded-fonts.ts
// containing the embedded font data plus a helper to decode it back to the
// original BDF text.

import { deflate } from "pako";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, extname, join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const bdfDir = join(__dirname, "..", "res", "bdf");
const outFile = join(__dirname, "..", "src", "font-data.ts");

const bdfFiles = readdirSync(bdfDir)
  .filter((file) => extname(file).toLowerCase() === ".bdf")
  .sort();

const entries = bdfFiles.map((file) => {
  const name = basename(file, extname(file));
  const bdfstring = readFileSync(join(bdfDir, file), "utf-8");
  const compressed = deflate(bdfstring);
  const base64 = Buffer.from(compressed).toString("base64");
  return { name, base64 };
});

const header = `// This file is auto-generated by tools/generate-fonts.js. Do not edit by hand.
// Run \`node tools/generate-fonts.js\` to regenerate it after changing files in res/bdf.

import { inflate } from "pako";
import { Base64 } from "js-base64";

/**
 * List of available fonts. Each font's \`bdf\` field holds its BDF content,
 * compressed with pako (zlib deflate) and base64-encoded.
 */
export const availableFonts: { name: string; bdf: string }[] = [
`;

const body = entries
  .map(
    ({ name, base64 }) =>
      `  { name: ${JSON.stringify(name)}, bdf: ${JSON.stringify(base64)} },`,
  )
  .join("\n");

const footer = `
];

/**
 * Decode a base64-encoded, pako-deflated string back into the original BDF
 * text.
 */
export function decodeEmbeddedFont(base64: string): string {
  const compressed = Base64.toUint8Array(base64);
  const decompressed = inflate(compressed);
  return new TextDecoder("utf-8").decode(decompressed);
}

/**
 * Get the original BDF text for an embedded font by name.
 */
export function getEmbeddedFontBDF(name: string): string {
  const font = availableFonts.find((font) => font.name === name);
  if (font === undefined) {
    throw new Error(\`Embedded font not found: \${name}\`);
  }
  return decodeEmbeddedFont(font.bdf);
}
`;

writeFileSync(outFile, `${header}${body}${footer}`);

console.log(`Wrote ${entries.length} font(s) to ${outFile}`);
