/**
 * Generates u8g2-compatible XBM C byte arrays straight from the in-memory
 * `IconSet` model (see `icon.ts`). u8g2's `drawXBM`/`drawXBMP` (and the C
 * `u8g2_DrawXBM`) expect true XBM packing — bits LSB-first within each byte,
 * one byte-row per pixel row — the same packing `scene-editor`'s Pen-shape
 * XBM export uses.
 *
 * The same packing also backs `generateIconSetJSON`, the machine-readable JSON
 * export for non-C toolchains.
 */

import { sanitizeIdentifier, type Box, type Icon } from "./icon";

export interface IconCodeOptions {
  lang: "c" | "cpp";
  useProgmem: boolean;
}

export function defaultIdentifier(icon: Icon): string {
  return sanitizeIdentifier(icon.name).toLowerCase();
}

/** Pack an icon's pixels into XBM bytes: LSB-first, byte-padded per row. */
export function toXBMBytes(box: Box, icon: Icon): number[] {
  const bytesPerRow = Math.ceil(box.w / 8);
  const bitmap = new Array(bytesPerRow * box.h).fill(0);
  for (let row = 0; row < box.h; row++) {
    for (let col = 0; col < box.w; col++) {
      if (!icon.pixels[row * box.w + col]) continue;
      const byteIndex = row * bytesPerRow + (col >> 3);
      bitmap[byteIndex] |= 1 << (col % 8);
    }
  }
  return bitmap;
}

function hex(value: number): string {
  return `0x${(value & 0xff).toString(16).padStart(2, "0")}`;
}

function chunkedHex(bytes: number[], perLine = 16): string[] {
  const lines: string[] = [];
  for (let i = 0; i < bytes.length; i += perLine) {
    lines.push(
      bytes
        .slice(i, i + perLine)
        .map(hex)
        .join(", ") + ",",
    );
  }
  return lines;
}

/**
 * Generate one `#define`/byte-array block per icon, usable directly with
 * `u8g2.drawXBM(x, y, w, h, <name>_bits)` / `u8g2_DrawXBM(&u8g2, x, y, w, h, <name>_bits)`.
 */
export function generateXBM(
  box: Box,
  icons: Icon[],
  options: IconCodeOptions,
): string {
  const lines: string[] = [];
  lines.push("// [BEGIN] generated by Pixpix");
  if (icons.length === 0) {
    lines.push("// No icons to export.");
  }
  const type = options.lang === "c" ? "uint8_t" : "unsigned char";
  const progmem =
    options.lang === "cpp" && options.useProgmem ? " PROGMEM" : "";
  for (const icon of icons) {
    const id = defaultIdentifier(icon);
    const bytes = toXBMBytes(box, icon);
    lines.push(`#define ${id}_width ${box.w}`);
    lines.push(`#define ${id}_height ${box.h}`);
    lines.push(`static const ${type} ${id}_bits[]${progmem} = {`);
    lines.push(...chunkedHex(bytes).map((line) => `  ${line}`));
    lines.push("};");
    lines.push("");
  }
  lines.push(
    options.lang === "c"
      ? "// Usage: u8g2_DrawXBM(&u8g2, x, y, <name>_width, <name>_height, <name>_bits);"
      : `// Usage: u8g2.${options.useProgmem ? "drawXBMP" : "drawXBM"}(x, y, <name>_width, <name>_height, <name>_bits);`,
  );
  lines.push("// [END] generated by Pixpix");
  return lines.join("\n");
}

/** One entry of the JSON export — an icon with its 1bpp XBM bytes. */
export interface IconJSONEntry {
  id: number;
  name: string;
  width: number;
  height: number;
  xbm: number[];
}

/**
 * Serialize the whole set as a JSON array of {@link IconJSONEntry}, so other
 * toolchains can consume the bitmaps without parsing generated C. `xbm` uses
 * the same packing as {@link generateXBM} — LSB-first, byte-padded per row.
 */
export function generateIconSetJSON(box: Box, icons: Icon[]): string {
  const entries: IconJSONEntry[] = icons.map((icon, index) => ({
    id: index,
    name: icon.name,
    width: box.w,
    height: box.h,
    xbm: toXBMBytes(box, icon),
  }));
  if (entries.length === 0) return "[]\n";
  // hand-formatted so each `xbm` stays on one line — `JSON.stringify(_, 2)`
  // would put every byte on its own.
  const body = entries
    .map(
      (entry) =>
        `  {\n` +
        `    "id": ${entry.id},\n` +
        `    "name": ${JSON.stringify(entry.name)},\n` +
        `    "width": ${entry.width},\n` +
        `    "height": ${entry.height},\n` +
        `    "xbm": [${entry.xbm.join(", ")}]\n` +
        `  }`,
    )
    .join(",\n");
  return `[\n${body}\n]\n`;
}
